### ISSUE TITLE
How to skip imported scss called inside my input file?

### ISSUE THREAD

**Issue by bluezald** [thgh/rollup-plugin-scss#100]
Hi, is it possible to skip building of dependent scss?

For example I have my own scss called `styles.scss` with a following dependency from node modules:

**styles.scss**
```scss
@import "@/../node_modules/third_party.scss";

// my scss here
```

In my rollup, I have set:
```js
scss({
    processor: () => postcss([autoprefixer()]),
    exclude: [path.join(__dirname, '../node_modules/'), 'node_modules/'],
    output: 'dist/styles.scss',
    failOnError: true,
    runtime: require('sass')
 })
```

But once the build is done, The font faces from the third-party scss is included, and I wanted to skip that. I'm only using the imported scss for the variables and colors.

**Comment by thgh** [comment]
The third party should create a separate file for the colors & variables so you can import that file specifically.

**Comment by bluezald** [comment]
Thanks @thgh That fixed it, and also I seem to have imported in another file the scss, that is why, I'm getting a lot of font faces.
