### ISSUE TITLE
Upgrade node-sass

### ISSUE THREAD

**Issue by mstijak** [thgh/rollup-plugin-scss#17]
This plugin uses an older version of node-sass which fails to install with Node 9.x. 
If you agree, I'll make a PR to upgrade the version of node-sass.

**Comment by thgh** [comment]
Sure!

**Comment by thgh** [comment]
On second thoughts, I don't think this will help. package.json only defines a minimum version and your project can use any version of node-sass starting from 4.5.3 and lower than 5.

Your pull request does not change the installed version of node-sass. You would need to update the lock file for that.
