### ISSUE TITLE
[!] Error: 'default' is not exported by src/alert.scss

### ISSUE THREAD

**Issue by tavurth** [thgh/rollup-plugin-scss#19]
[Sample repository](https://github.com/tavurth/rollup-scss-test)

```javascript
import styles from './styles.scss';
```
Causes the error:
`[!] Error: 'default' is not exported by src/styles.scss`

**Comment by thgh** [comment]
Please check out the usage section in the readme.

**Comment by tavurth** [comment]
Changing the command to 
```javascript
import './styles.scss`
...
<div className='alert' />
```

Seems to have a  different result, in that the class is not loaded. Any ideas?

**Comment by thgh** [comment]
You might be looking for css modules, modular css or styled components. This package simply combines the imported & compiled scss files into `bundle.css`

**Comment by elevatebart** [comment]
Hello @thgh 

I am looking for this as well.
According to https://css-tricks.com/getting-javascript-to-talk-to-css-and-sass/ you can make scss and js talk this way. 
I understand it was a choice not to make it work at first but could it be added?

Thank you for the great lib
