### ISSUE TITLE
Compression an injection feature request

### ISSUE THREAD

**Issue by wwwebman** [thgh/rollup-plugin-scss#21]
Hello, thanks for sharing!

Is there any plan to implement next features: 
1. possibility to compress/minify  output css
2. bundle css together with bundle.js (aka inject feature webpack loaders apply)

I guess there is possibility to do point 1 one by own handler inside output() method, right?

**Comment by thgh** [comment]
1. It would be nice if the plugin would look at process.env.NODE_ENV and look for minifier in package.json and would enable minification.
2. Could be an option

I'm open to backwards compatible PRs 👍

**Comment by thgh** [comment]
1. See https://github.com/thgh/rollup-plugin-scss/tree/v3#examples
2. There is now an `insert` option

**Comment by endday** [comment]
> 1. See https://github.com/thgh/rollup-plugin-scss/tree/v3#examples
> 2. There is now an `insert` option

when is the `insert` option，the examples can't find this.
