### ISSUE TITLE
The ongenerate hook used by plugin css is deprecated. The generateBundle hook should be used instead.

### ISSUE THREAD

**Issue by zech** [thgh/rollup-plugin-scss#25]
Using the latest version of:

`npm i -D rollup-plugin-scss@latest` (currently 0.4.0)

triggers the plugin error:

> The ongenerate hook used by plugin css is deprecated. The generateBundle hook should be used instead.

when i'm using rollup v1+

This is obviously fixed in the repo in the latest commit but not for the npm package

https://github.com/thgh/rollup-plugin-scss/blob/416047c8beabf44927a7ddf2cc74b29a02c6cae6/index.es.js#L71

Is it possible for you to release the fix to npm as well? Last release was 0.4.0 about a year ago.

Tim

**Comment by thgh** [comment]
Thanks for the reminder!
