### ISSUE TITLE
High severity vulnerability

### ISSUE THREAD

**Issue by ZaDarkSide** [thgh/rollup-plugin-scss#28]
```  High            Arbitrary File Overwrite
  Package         tar                                                  
  Patched in      >=4.4.2                            
  Dependency of   rollup-plugin-scss [dev]     
  Path            rollup-plugin-scss > node-sass > node-gyp > tar
  More info       https://npmjs.com/advisories/803
```

A solution would be to update in ```packages.json``` node-sass version to latest

**Comment by thgh** [comment]
tar has been fixed
node-gyp has been fixed
node-sass is working on it: https://github.com/sass/node-sass/issues/2625

Updating `package.json` shows same audit warning, so I will wait until node-sass is fixed.

**Comment by web3devin** [comment]
@thgh , This is no longer an issue; if you still want to close the issue.

**Comment by thgh** [comment]
Alrighty
