### ISSUE TITLE
Injecting css path through the bundle

### ISSUE THREAD

**Issue by mfrachet** [thgh/rollup-plugin-scss#29]
Is this possible to automatically import the css sheet while importing the js module?

Actually, I'm finally having to output:

- a js file
- a css file

And I wanted to add the css file to the dom through the js one.

Is this something feasible in the current lib state?

Thanks for the job by the way 💪

**Comment by thgh** [comment]
Yes, looks feasible. Would you embed the content of a style tag and then add the style tag dynamically? Or create a link tag that loads the css file? The latter might require an extra basePath parameter.

PR welcome!

**Comment by mfrachet** [comment]
My use case concerns the link addition 😊

**Comment by thgh** [comment]
Here is a start https://github.com/thgh/rollup-plugin-scss/commit/4a0645065d878285a8d3cb9ba8597384fa193cd5
(I did not test)
