### ISSUE TITLE
Generating a JS file that I do not want

### ISSUE THREAD

**Issue by jobelenus** [thgh/rollup-plugin-scss#35]
The README is not up to date with newer versions of rollup

I have one `global.scss` file. The plugin creates a `global.css` file like I expect but it also creates a `global` file with no extension and just the `use strict;` javascript on the only line. If I just want to crunch scss —> css why am I getting a js file as well?

Here is the output of rollup:
```
bundles public/scss/global.scss → public/global...
(!) Generated an empty bundle
public/global.css 995 B
created public/global in 5ms
```

Here is the rollup.config.js for this section:
```
{
	input: 'public/scss/global.scss',
	output: {
    file: 'public/global',
    format: 'cjs',
  },
	plugins: [
		scss()
	]
};
```

This is not the only plugin in the rollup, I am using Svelte as well.

**Comment by thgh** [comment]
Rollup is an ES modules bundler and will always output JavaScript. Don't use a scss file as input. Import it from your svelte app.
