### ISSUE TITLE
Consider to use "sass" instead of "node-sass"

### ISSUE THREAD

**Issue by dkorobeinikov** [thgh/rollup-plugin-scss#39]
Is it possible to replase `node-sass` package with `sass`? 

`sass` has more frequent updates, supports [newest SASS features](https://sass-lang.com/blog/the-module-system-is-launched) and requires much less dependencies (according to npm.anvaka.com [`sass` has 18 deps](http://npm.anvaka.com/#/view/2d/sass)) while [`node-sass` needs 179](http://npm.anvaka.com/#/view/2d/node-sass).
Also, `sass` doesn't depend on NodeJS C++ Addons

In most cases `sass` has the same API as `node-sass`, so it shouldn't be much problems on migrating.

**Comment by thgh** [comment]
PR welcome! I would then prefer to still use node-sass because it's faster. So having both as peerdependencies and allowing developers to choose which one? This would be a major version bump.

**Comment by thgh** [comment]
Released the `sass` option in v2.4.0
