### ISSUE TITLE
Update documentation on usage of indented syntax

### ISSUE THREAD

**Issue by Robin-Hoodie** [thgh/rollup-plugin-scss#50]
I just spent a couple of hours figuring out why I kept getting syntax errors along the lines of:

`Error: expected ";".`

I figured out pretty quickly that the plugin was parsing this without using the indented syntax, even though my files were being imported as `.sass` files, not  `.scss` files.

After digging through the [Sass Javascript API options](https://sass-lang.com/documentation/js-api#options) I found the `indentedSyntax` option which was passed through by the plugin.

I think the documentation should:

1. Make it more clear that you can use the options of the Sass Javascript API
2. Especially point out the `indentedSyntax` option

I'm happy to make these changes to the docs as a PR if needed.

**Comment by Robin-Hoodie** [comment]
One other thing on this: while looking through [the sourcecode](https://github.com/thgh/rollup-plugin-scss/blob/a11c0a0f585c4c9cd7a18248aaa28cd2c2782b20/index.es.js#L6) I noticed that the `include` option is being used, though it doesn't seem to be documented either.

**Comment by thgh** [comment]
PR welcome 😄
