### ISSUE TITLE
Using postCSS? Are the docs correct?

### ISSUE THREAD

**Issue by Elvanos** [thgh/rollup-plugin-scss#54]
Is there any additional step to using the postCSS with this plugin? Does someone else need to be installed?

I tried copy-pasting the example code into my rollup config file and I am getting undefined results where my styles are supposed to come out. The whole script works perfectly fine without the postCSS addition, so the issue is most certainly there.

The code I am using in the config file: 
```
 scss({ 
      output: false,
      processor: css => postcss([autoprefixer({ overrideBrowserslist: "Edge 18" })])
    }),
```

**Comment by thgh** [comment]
Probably import postcss? @geotrev

**Comment by thgh** [comment]
Here is an example of postcss: https://github.com/thgh/rollup-plugin-scss/tree/v3#examples
