### ISSUE TITLE
Move node-sass to optionalDependencies

### ISSUE THREAD

**Issue by weizhenye** [thgh/rollup-plugin-scss#56]
node-sass requires download binary from Internet, which is usually not provided by proxy service like Artifactory, it needs extra works to make `npm i` work in enterprise intranet.

If node-sass is moved to [optionalDependencies](https://docs.npmjs.com/files/package.json#optionaldependencies), it can be ignored by `npm i --no-optional`. And it should not affect normal `npm i`.

**Comment by thgh** [comment]
PR welcome! But it probably makes more sense for you to use https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by nhoizey** [comment]
This would also be useful if using Dart Sass (npm `sass` package), I guess.

**Comment by thgh** [comment]
Released in v2.6.1 🎉
