### ISSUE TITLE
Add documentation regarding "includePath" property

### ISSUE THREAD

**Issue by ashvin777** [thgh/rollup-plugin-scss#64]
By looking at the doc, I found that is there is no way to use `includePath`, however by looking into code that is actually possible. 
```javascript
    scss({
      output: true,
      processor: () => postcss([autoprefixer()]),
      includePaths: [path.join(__dirname, '../../node_modules/'), 'node_modules/']
    }),
```

Please update the documentation to mention all such properties.

**Comment by ashvin777** [comment]
Any update ?

**Comment by thgh** [comment]
Well, it's mentioned in the first sentence under Options:
> Options are passed to the sass compiler

I will add your example to the README
