### ISSUE TITLE
spaces are removed inside calc, if used on property

### ISSUE THREAD

**Issue by yairEO** [thgh/rollup-plugin-scss#67]
Hi, I came across a very bizarre thing:

### Setup: 

    scss({ output: false, watch: 'src/styles', })

----
Below CSS:

```css
opacity: calc(var(--a) - var(--b));
```
    
Results in an *invalid* CSS `calc` due to the lack of *whitespace* between the mathematical operation:
 
```css
    opacity: calc(var(--a)-var(--b));
```
  
Weirdly, this does not happen here:

```css
-foo: calc(var(--a) - var(--b));
opacity: var(-foo);
```

Seems to work ok in [sassmeister](https://www.sassmeister.com) so I thought it might be specifically related to this package.

**Comment by thgh** [comment]
This package does not transform css.  It's probably related to `node-sass` or `sass`.

**Comment by yairEO** [comment]
yeah I thought it might not be actually doing anything.. thanks tho

**Comment by yairEO** [comment]
I know it does not transform sass to css but maybe it does some afterwards manipulation of some sort that removes those spaces.. it's weird because this behaviour only happens with `rollup-plugin-scss`
