### ISSUE TITLE
Support PostCSS/processor, similar to rollup-plugin-sass

### ISSUE THREAD

**Issue by viveleroi** [thgh/rollup-plugin-scss#8]
I need to pass the compiled css through postcss but am not seeing any built-in options. I'll likely toy around with a custom `output` function to do what I need in the meantime.

**Comment by thgh** [comment]
Seems doable and will accept a PR for that!

**Comment by thgh** [comment]
Check out v0.4.0 🎉

**Comment by pablote** [comment]
Is there an example on how to set this up? I didn’t see any mention of this. Thanks!
